Repository IIIF/cookbook-recipes, pull requests merged in 2020-10, with the labels that each got.

#197 Recipe #0005 — Image Service for single image
  _includes/links.md
  index.md
  recipe/0001-mvm-image/index.md
  recipe/0005-image-service/index.md
  recipe/0005-image-service/manifest.json
Labels: meta: ready-for-trc

#203 Recipe #0202 -- Load manifest beginning with a specific canvas
  _includes/links.md
  index.md
  recipe/0202-start-canvas/index.md
  recipe/0202-start-canvas/manifest.json
Labels: content: image, meta: ready-for-trc

#208 Adding license information for 30min clock
  recipe/0003-mvm-video/index.md
  recipe/0003-mvm-video/manifest.json
  recipe/0015-start/index.md
  recipe/0015-start/manifest.json
Labels: meta: ready-to-merge

#153 Recipe #0009 — Simplest Manifest - Multiple Related Images (book, etc.)
  _includes/links.md
  index.md
  recipe/0009-book-1/index.md
  recipe/0009-book-1/manifest.json
Labels: meta: approved-by-trc, meta: ready-to-merge

#136 Opera Recipes
  _includes/links.md
  index.md
  recipe/0026-toc-opera/index.md
  recipe/0026-toc-opera/manifest.json
  recipe/0064-opera-one-canvas/index.md
  recipe/0064-opera-one-canvas/manifest.json
  recipe/0065-opera-multiple-canvases/index.md
  recipe/0065-opera-multiple-canvases/manifest.json
Labels: meta: approved-by-trc, meta: ready-to-merge

#148 Recipe #0010 — Book (viewingDirection variations)
  _includes/links.md
  index.md
  recipe/0010-book-2-viewing-direction/index.md
  recipe/0010-book-2-viewing-direction/manifest-rtl.json
  recipe/0010-book-2-viewing-direction/manifest-ttb.json
Labels: meta: approved-by-trc, meta: ready-to-merge

#178 Recipe #0004 — Image different size to canvas
  _includes/links.md
  index.md
  recipe/0004-canvas-size/index.md
  recipe/0004-canvas-size/manifest.json
Labels: meta: ready-for-trc
