Repository IIIF/cookbook-recipes, pull requests merged in 2021-04, with the labels that each got.

#183 Represent Canvas Fragment as a Geographic Area on a Web Map
  _includes/links.md
  index.md
  recipe/0139-geolocate-canvas-fragment/images/leaflet_example.png
  recipe/0139-geolocate-canvas-fragment/images/piece2.png
  recipe/0139-geolocate-canvas-fragment/index.md
  recipe/0139-geolocate-canvas-fragment/manifest.json
Labels: maps, meta: ready-for-trc

#221 both annotations on same Annotation Page
  recipe/0064-opera-one-canvas/index.md
  recipe/0064-opera-one-canvas/manifest.json
Labels: meta: approved-by-trc, meta: ready-to-merge

#231 Recipe #0230—Chronology with navDate
  _includes/links.md
  index.md
  recipe/0230-navdate/index.md
  recipe/0230-navdate/navdate-collection.json
  recipe/0230-navdate/navdate_map_1-manifest.json
  recipe/0230-navdate/navdate_map_2-manifest.json
Labels: meta: approved-by-trc

#228 0030-multi-volume
  _includes/links.md
  index.md
  recipe/0030-multi-volume/collection.json
  recipe/0030-multi-volume/index.md
  recipe/0030-multi-volume/manifest_v1.json
  recipe/0030-multi-volume/manifest_v2.json
Labels: content: text, meta: approved-by-trc
