Repository IIIF/cookbook-recipes, pull requests merged in 2021-03, with the labels that each got.

#204 Recipe #0024 - Book with Table of contents (ranges)
  _includes/links.md
  index.md
  recipe/0024-book-4-toc/index.md
  recipe/0024-book-4-toc/manifest.json
  recipe/0024-toc-book-chapters/index.md
Labels: content: text, meta: ready-for-trc

#227 0029 metadata
  _includes/links.md
  index.md
  recipe/0029-metadata-anywhere/index.md
  recipe/0029-metadata-anywhere/manifest.json
Labels: meta: ready-for-trc

#223 0219 using caption file
  _includes/links.md
  index.md
  recipe/0219-using-caption-file/index.md
  recipe/0219-using-caption-file/manifest.json
Labels: meta: approved-by-trc

#218 Recipe #0053—Related Machine-Readable Resources with seeAlso
  _includes/links.md
  index.md
  recipe/0053-seeAlso/ezukushi.xml
  recipe/0053-seeAlso/index.md
  recipe/0053-seeAlso/manifest.json
Labels: meta: approved-by-trc
