Repository IIIF/cookbook-recipes, pull requests merged in 2023-06, with the labels that each got.

#392 Add an example for an image in annotation
  _includes/links.md
  index.md
  recipe/0377-image-in-annotation/index.md
  recipe/0377-image-in-annotation/manifest.json
Labels: meta: approved-by-trc

#252 Changing Newspaper recipe to be rendering rather than seeAlso
  Gemfile.lock
  _includes/links.md
  index.md
  recipe/0068-newspaper/index.md
  recipe/0068-newspaper/newspaper_issue_1-alto_p1.xml
  recipe/0068-newspaper/newspaper_issue_1-alto_p2.xml
  recipe/0068-newspaper/newspaper_issue_1-anno_p1.json
  recipe/0068-newspaper/newspaper_issue_1-anno_p2.json
  recipe/0068-newspaper/newspaper_issue_1-manifest.json
  recipe/0068-newspaper/newspaper_issue_2-alto_p1.xml
  recipe/0068-newspaper/newspaper_issue_2-alto_p2.xml
  recipe/0068-newspaper/newspaper_issue_2-anno_p1.json
  recipe/0068-newspaper/newspaper_issue_2-anno_p2.json
  recipe/0068-newspaper/newspaper_issue_2-manifest.json
  recipe/0068-newspaper/newspaper_title-collection.json
  scripts/validate.py
  scripts/validate.sh
Labels: meta: approved-by-trc, meta: ready-to-merge, meta: correction

#414 Address canvas target typo on #0014 Manifest.
  recipe/0014-accompanyingcanvas/manifest.json
Labels: meta: ready-to-merge
