Repository IIIF/cookbook-recipes, pull requests merged in 2024-02, with the labels that each got.

#317 #283 Missing images in a sequence
  _includes/links.md
  index.md
  recipe/0283-missing-image/index.md
  recipe/0283-missing-image/manifest.json
Labels: meta: approved-by-trc, content: image, meta: ready-to-merge

#454 Fix invalid html in `requiredStatement` for #0008
  recipe/0008-rights/manifest.json
Labels: meta: ready-to-merge

#455 Fix inaccurate GeoJSON in annotation for #0139
  recipe/0139-geolocate-canvas-fragment/manifest.json
Labels: meta: ready-to-merge

#458 Fix the width and height on specific point canvas.
  recipe/0135-annotating-point-in-canvas/manifest.json
Labels: meta: ready-to-merge, meta: correction

#460 0117 add image thumbnail patch
  recipe/0117-add-image-thumbnail/manifest.json
Labels: meta: ready-to-merge

#456 Update example text in #0117 for accuracy
  _includes/links.md
  index.md
  recipe/0117-add-image-thumbnail/index.md
Labels: meta: ready-to-merge

#462 Adding test to check jpg mime type
  recipe/0154-geo-extension/manifest.json
  recipe/0232-image-thumbnail-canvas/index.md
  recipe/0232-image-thumbnail-canvas/manifest-image.json
  recipe/0240-navPlace-on-canvases/manifest.json
  scripts/validate.sh
Labels: meta: correction
