Repository IIIF/cookbook-recipes, pull requests merged in 2025-01, with the labels that each got.

#574 Change: Make MIME type for MP3 item audio/mpeg
  recipe/0434-choice-av/manifest.json
Labels: meta: correction

#573 Change: Add viewer highlight behavior caveat to #266
  recipe/0266-full-canvas-annotation/index.md
Labels: meta: ready-to-merge, meta: correction

#521 Recipe #309 annotation collections
  _includes/links.md
  index.md
  recipe/0309-annotation-collection/anno_coll.json
  recipe/0309-annotation-collection/anno_p1.json
  recipe/0309-annotation-collection/anno_p2.json
  recipe/0309-annotation-collection/diagram-309.graffle
  recipe/0309-annotation-collection/diagram-309.png
  recipe/0309-annotation-collection/index.md
  recipe/0309-annotation-collection/manifest.json
Labels: meta: approved-by-trc, meta: ready-to-merge

#564 0540 link for opening multiple canvases
  _includes/links.md
  index.md
  recipe/0540-link-for-opening-multiple-canvases/annotation.json
  recipe/0540-link-for-opening-multiple-canvases/canvases_sides_by_side.jpeg
  recipe/0540-link-for-opening-multiple-canvases/index.md
  recipe/0540-link-for-opening-multiple-canvases/manifest-2.json
  recipe/0540-link-for-opening-multiple-canvases/manifest.json
Labels: meta: approved-by-trc
